
theme: jekyll-theme-cayman

baseurl: "/pages" # change this to the subpath of your site, e.g. /blog. Leave it empty if you don't need it.
url: "https://cdphrusers.github.io" # change this to the base hostname & protocol for your site



